### ISSUE TITLE
[Question] Change title apply button & title search

### ISSUE THREAD

**Issue by weebsproject** [TheAlphamerc/filterlist#26]
is there anything to do to change the title on apply button  FilterListDelegate.show...

![image](https://user-images.githubusercontent.com/75978848/152739706-5ecdbd2f-6123-4d42-b61e-950f7aa6b9e9.png)
based on that pict, it's only available to change applybuttonstyle, how to change applybuttontitle ?

also

![image](https://user-images.githubusercontent.com/75978848/152739904-19f4e5f2-8330-4a5d-bcd6-91cc955d260a.png)
how to rename label search as an example I want to change from Search here.. to Maghanap dito..
![image](https://user-images.githubusercontent.com/75978848/152740009-8630cc38-e3f2-47eb-8114-637c41b9915f.png)

thanks,

**Comment by TheAlphamerc** [comment]
@weebsproject As of now changing apply button title feature is missing. To change the search field hint text use `searchFieldHint` parameter.
