### ISSUE TITLE
[Question] initial selected 

### ISSUE THREAD

**Issue by weebsproject** [TheAlphamerc/filterlist#30]
at initstate I've done to add selectedlistdate 

but when i clicked the filter list, the filterlistdelegate not giving the checklist.

![image](https://user-images.githubusercontent.com/75978848/159110222-03f12fa7-dfbf-4fba-938f-d5f1defc1a58.png)

am i wrong to write below code ?
![image](https://user-images.githubusercontent.com/75978848/159110123-40ba4f78-0b49-49f9-b07e-47f779909933.png)

btw ive logs the list that i input into the selectedlist.
it show, but only at the filterlistdelegate that not giving the checklist

**Comment by TheAlphamerc** [comment]
This is fixed in version 1.0.3
