### ISSUE TITLE
Maximum selectable Chips

### ISSUE THREAD

**Issue by xxceonxx** [TheAlphamerc/filterlist#36]
Hello,

it will be great to get control of a maximum amount of selectable Chips. Like the [maxLength] propertie in TextFields.

**Comment by TheAlphamerc** [comment]
Yeah, it will be a good feature.

**Comment by MxD-js** [comment]
+1 

Is there a workaround to implement such feature?

**Comment by TheAlphamerc** [comment]
It is available in version 1.0.3
