### ISSUE TITLE
Selected Text Count on bottom.

### ISSUE THREAD

**Issue by Tristannos** [TheAlphamerc/filterlist#38]
**Is your feature request related to a problem? Please describe.**
For me it is too much space, i would like the chips directly under the name and in the same time display how many are selected.

Make an option to display "selectedItemsCountOnBottom" boolean.

![Screenshot 2022-12-05 at 10 19 18](https://user-images.githubusercontent.com/55278228/205603476-b40fb1fe-af21-4b24-a52c-1ac17a6c3faa.png)

**Comment by TheAlphamerc** [comment]
SelctedItemCount is better to place on top. If we plan to place it on the bottom then either we have to place it 

1. On top of the button bar. ( `It will take some space as it is taking on top` )
2. Just after the items list. (` Will not be visible if there are lot of items in list until list is scrolled to bottom`)

**Comment by Tristannos** [comment]
Oh oke,

On top of the button bar is not the best for mee because that i want to remove that button :)

But on the bottom of the list is the best option i think.
As an option only.

**Comment by TheAlphamerc** [comment]
Closing this issue for now as there is no plan to put this on the bottom.
