### ISSUE TITLE
[Question]  FilterListDialog.display is missing i18n parameters for "searchFieldHintText"

### ISSUE THREAD

**Issue by AlexBaklizki** [TheAlphamerc/filterlist#41]
I am using your package and it is awesome. Thank you a lot for it :)

Actually, in the Code documentation I can see that it should be possible to set a string for the searchFieldHintText:
![grafik](https://user-images.githubusercontent.com/130476179/231188538-c8789abc-311d-4e3b-8e73-8d6bd94f2b44.png)

But when I initialize the Dialog with FilterListDialog there is no possibility to set the string. Actually the search string is still showing up in english language.
![grafik](https://user-images.githubusercontent.com/130476179/231189137-438635e4-5c79-4e9a-b52d-c2b17a9dee83.png)

Will be there a fix?

**Comment by TheAlphamerc** [comment]
It will be fixed in newer version
