### ISSUE TITLE
FilterListDelegateThemeData does not apply changed theme data

### ISSUE THREAD

**Issue by moses-sichone** [TheAlphamerc/filterlist#43]
FilterListDelegate single selection text color cannot be changed from the default black.
I tried styling the text using FilterListDelegateThemeData but the theme changes aren't applied.
Am i  supposed to style the list text in a different way??

**Comment by TheAlphamerc** [comment]
By using tileTextStyle` inside `FilterListDelegateThemeData` it's color can be changed.
