### ISSUE TITLE
[Bug] FilterListDelegate bug when select item

### ISSUE THREAD

**Issue by tnl9294** [TheAlphamerc/filterlist#47]
**Describe the bug**
In FilterListDelegate mode, when I select the item, the item that is not visible is already selected (usually on the 2nd attempt). however when i click on the search box the item shows as selected.

**To Reproduce**
1. Select item -> not show selected (usually on the 2nd attempt).
2. Click on the search box -> show selected.

**Expected behavior**
Item show selected when select.

**Screenshots**
![Bug](https://github.com/TheAlphamerc/filterlist/assets/53172206/83f1ab12-bc10-4555-8d3c-d3a1102861c8)

**Smartphone**
 - Device: [Samsung M51]
 - OS: [Android 12]

**Comment by TheAlphamerc** [comment]
This is fixed in version 1.0.3.
