### ISSUE TITLE
Search filter doesn't work after empty list

### ISSUE THREAD

**Issue by steveroseik** [TheAlphamerc/filterlist#49]
**Describe the bug**
When you use the search textfield to filter the list, if you reach a dead end and your keyword doesn't correspond to items.
You then have to delete the whole keyword instead of just fixing your keyword typo in order to get the filter to work again.

for example:

List: 
- yorkshire
- bulldog

if your keyword is "yorf": result is 0 items
then if you fix the keyword to "yor": result is still 0 items
until the you clear all the text and type "y": result 1 item

**To Reproduce**

Create a list and use search filters on it

**Expected behavior**
expected to have the keyword filter fire for each change in textfield

**Comment by bradfrizzell** [comment]
Plus one on this!

**Comment by bradfrizzell** [comment]
The bug is this line - it shouldn't be in this if block. https://github.com/TheAlphamerc/filterlist/blob/master/lib/src/filter_list_widget.dart#L191

**Comment by TheAlphamerc** [comment]
This is fixed in version 1.0.3
