### ISSUE TITLE
Flutter upgrade to 3.22 and Getting Error for TextTheme Caption.

### ISSUE THREAD

**Issue by MonkeyDrone** [TheAlphamerc/filterlist#50]
/C:/Users/xxx/AppData/Local/Pub/Cache/hosted/pub.dev/filter_list-1.0.2/lib/src/filter_list_widget.dart:193:58: Error: The getter 'caption' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/D:/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'caption'.
                      style: Theme.of(context).textTheme.caption,
                                                         ^^^^^^^
Target kernel_snapshot failed: Exception

After upgrading to Flutter 3.22.
Getting textTheme.caption error when compiling.

**Comment by MonkeyDrone** [comment]
Fix is to bump the SDK and Flutter version in pubspec file.
sdk: '>=3.3.4 <4.0.0'
flutter: ">=3.22.0"
cloned it and made changes in pubspec to this and it works.

**Comment by simonkenyongithub** [comment]
would you please consider making a release of 1.0.3?

**Comment by TheAlphamerc** [comment]
The new version is released with an updated flutter version.
